[2023-04-23T18:38:03.279-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trabajo_practico.TopCTR manual__2023-04-23T21:37:59.341386+00:00 [queued]>
[2023-04-23T18:38:03.282-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trabajo_practico.TopCTR manual__2023-04-23T21:37:59.341386+00:00 [queued]>
[2023-04-23T18:38:03.282-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T18:38:03.282-0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-23T18:38:03.282-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T18:38:03.297-0300] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): TopCTR> on 2023-04-23 21:37:59.341386+00:00
[2023-04-23T18:38:03.299-0300] {standard_task_runner.py:55} INFO - Started process 31059 to run task
[2023-04-23T18:38:03.301-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'trabajo_practico', 'TopCTR', 'manual__2023-04-23T21:37:59.341386+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dag_tp.py', '--cfg-path', '/tmp/tmpa3c3tzcd']
[2023-04-23T18:38:03.301-0300] {standard_task_runner.py:83} INFO - Job 48: Subtask TopCTR
[2023-04-23T18:38:03.333-0300] {task_command.py:389} INFO - Running <TaskInstance: trabajo_practico.TopCTR manual__2023-04-23T21:37:59.341386+00:00 [running]> on host pepino-ThinkPad-E15-Gen-2
[2023-04-23T18:38:03.425-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trabajo_practico
AIRFLOW_CTX_TASK_ID=TopCTR
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T21:37:59.341386+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T21:37:59.341386+00:00
[2023-04-23T18:38:03.428-0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_tp.py", line 50, in TopCTR
    top_ctr = datos_filtrados.groupby(['advertiser_id','product_id'])['type'].value_counts().reset_index().pivot(index = ['advertiser_id','product_id'], columns='type', values='count').reset_index()
AttributeError: 'dict' object has no attribute 'groupby'
[2023-04-23T18:38:03.430-0300] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=trabajo_practico, task_id=TopCTR, execution_date=20230423T213759, start_date=20230423T213803, end_date=20230423T213803
[2023-04-23T18:38:03.443-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 48 for task TopCTR ('dict' object has no attribute 'groupby'; 31059)
[2023-04-23T18:38:03.473-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T18:38:03.541-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
