[2023-04-23T18:39:06.864-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trabajo_practico.TopCTR manual__2023-04-23T21:37:59.341386+00:00 [queued]>
[2023-04-23T18:39:06.867-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trabajo_practico.TopCTR manual__2023-04-23T21:37:59.341386+00:00 [queued]>
[2023-04-23T18:39:06.868-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T18:39:06.868-0300] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-04-23T18:39:06.868-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T18:39:06.882-0300] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): TopCTR> on 2023-04-23 21:37:59.341386+00:00
[2023-04-23T18:39:06.885-0300] {standard_task_runner.py:55} INFO - Started process 31242 to run task
[2023-04-23T18:39:06.886-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'trabajo_practico', 'TopCTR', 'manual__2023-04-23T21:37:59.341386+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_tp.py', '--cfg-path', '/tmp/tmppwwrghed']
[2023-04-23T18:39:06.886-0300] {standard_task_runner.py:83} INFO - Job 50: Subtask TopCTR
[2023-04-23T18:39:06.916-0300] {task_command.py:389} INFO - Running <TaskInstance: trabajo_practico.TopCTR manual__2023-04-23T21:37:59.341386+00:00 [running]> on host pepino-ThinkPad-E15-Gen-2
[2023-04-23T18:39:06.997-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trabajo_practico
AIRFLOW_CTX_TASK_ID=TopCTR
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T21:37:59.341386+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T21:37:59.341386+00:00
[2023-04-23T18:39:07.001-0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/pepino/.virtualenvs/apache_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/pepino/Desktop/Maestría Udesa/Segundo Año/Programación Avanzada para grandes volúmenes de datos/airflow/dags/dag_tp.py", line 50, in TopCTR
    top_ctr = datos_filtrados.groupby(['advertiser_id','product_id'])['type'].value_counts().reset_index().pivot(index = ['advertiser_id','product_id'], columns='type', values='count').reset_index()
AttributeError: 'dict' object has no attribute 'groupby'
[2023-04-23T18:39:07.002-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=trabajo_practico, task_id=TopCTR, execution_date=20230423T213759, start_date=20230423T213906, end_date=20230423T213907
[2023-04-23T18:39:07.015-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 50 for task TopCTR ('dict' object has no attribute 'groupby'; 31242)
[2023-04-23T18:39:07.058-0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T18:39:07.068-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
